<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="itext.commons">
      <HintPath>C:\Users\Bhavin\source\repos\eComCropper\backend\bin\Debug\net8.0\itext.commons.dll</HintPath>
    </Reference>
    <Reference Include="itext.io">
      <HintPath>C:\Users\Bhavin\source\repos\eComCropper\backend\bin\Debug\net8.0\itext.io.dll</HintPath>
    </Reference>
    <Reference Include="itext.kernel">
      <HintPath>C:\Users\Bhavin\source\repos\eComCropper\backend\bin\Debug\net8.0\itext.kernel.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.26\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\8.0.26\Microsoft.Extensions.Logging.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
